Features/widget test amountcard
blackminystudio/tacklepay pull request #34
Opened 2024-12-16 20:19 UTC by krushnakantanayak

### Release

1.0.0
https://blackminystudio.atlassian.net/browse/TPA-64

### Description
-Valid Balance Amount: Ensures correct balance amount and label are displayed.
-Large Balance Amount: Verifies that very large amounts are truncated and display an ellipsis.
-Empty Balance Amount: Confirms correct rendering when no amount is provided.

- 

### Screenshots

<img width="1163" alt="Amount_card_test" src="https://github.com/user-attachments/assets/ef4a206c-0ca2-41a7-8f63-2ed348dfecff" />

### Tips

Any tips for testing it?

---

### IMPORTANT:

- (REQUIRED) Coverage Screenshots for the tests written
- (REQUIRED) UI Screenshots for the UI implementation written

### Author preparation checklist

- [ ] Current branch is rebased with latest 'Staging' branch
- [ ] PR is targeting only one issue
- [ ] Commit messages are descriptive, consistent, and follow the project's guidelines.
- [ ] Branch name matches with at least `<jira link reference>-<short change description>`
- [ ] Primary reviewer is set as assignee to the PR
- [ ] No unnecessary changes on `pubspec.lock`
- [ ] All added TODOs have associated Github issue references
- [ ] \*.iml and, pubsepc_overrides.yaml are not checkedin
- [ ] All hard coded strings are present in constants file

### Primary reviewer checklist

- [ ] All items in the author checklist is checked or not applicable
- [ ] All files including .lock and assets are reviewed
- [ ] Reasonable UI flows/cases related to the change are manually tested
- [ ] No commented-out code or unnecessary debug statements.
- [ ] No spelling or grammatical errors in code comments or documentation.
- [ ] No sensitive data (e.g., API keys, credentials) is hardcoded or exposed.
- [ ] The branch is up-to-date with the target branch (e.g., staging).
- [ ] The code adheres to established coding standards.

### Pre-merge checklist

- [ ] Two approvals received. (Changes affecting automatic PR verification, like new linter rules, formatting rules, Github workflow configurations)

---

2024-12-17 06:54 UTC, quiteachaos requested changes

2024-12-17 06:54 UTC, quiteachaos commented on test/widgets/balance_amount_test.dart
> +      expect(find.text('10000'), findsOneWidget);
expect 10,000
it should be formatted
change the balance amount file if req.

2024-12-17 06:54 UTC, quiteachaos commented on test/widgets/balance_amount_test.dart
> +        'Then it should display an empty space and the label text',
Then it should display zero with rupee symbol and label text

update the test case here accordingly and the original file if req.

2024-12-17 16:37 UTC, krushnakantanayak commented on test/widgets/balance_amount_test.dart
> +      expect(find.text('10000'), findsOneWidget);
resolve the issue

2024-12-17 16:37 UTC, krushnakantanayak commented on test/widgets/balance_amount_test.dart
> +        'Then it should display an empty space and the label text',
updated

2024-12-18 15:59 UTC, quiteachaos approved these changes

2024-12-24 16:17 UTC, merged