Widget Test: SummaryCard
blackminystudio/tacklepay pull request #40
Opened 2024-12-17 15:06 UTC by krushnakantanayak

### Release

1.0.0
https://blackminystudio.atlassian.net/browse/TPA-67

### Description

- vs Last Month" Text Validation
- Percentage Text Validation
- Amount Display Validation
- Header Text and Background Color Validation

### Screenshots

<img width="1207" alt="summary_card_test" src="https://github.com/user-attachments/assets/19332452-bb35-400b-913b-a9c13475bb58" />

### Tips

Any tips for testing it?

---

### IMPORTANT:

- (REQUIRED) Coverage Screenshots for the tests written
- (REQUIRED) UI Screenshots for the UI implementation written

### Author preparation checklist

- [x] Current branch is rebased with latest 'Staging' branch
- [x] PR is targeting only one issue
- [x] Commit messages are descriptive, consistent, and follow the project's guidelines.
- [ ] Branch name matches with at least `<jira link reference>-<short change description>`
- [x] Primary reviewer is set as assignee to the PR
- [x] No unnecessary changes on `pubspec.lock`
- [x] All added TODOs have associated Github issue references
- [x] \*.iml and, pubsepc_overrides.yaml are not checkedin
- [x] All hard coded strings are present in constants file

### Primary reviewer checklist

- [ ] All items in the author checklist is checked or not applicable
- [ ] All files including .lock and assets are reviewed
- [ ] Reasonable UI flows/cases related to the change are manually tested
- [ ] No commented-out code or unnecessary debug statements.
- [ ] No spelling or grammatical errors in code comments or documentation.
- [ ] No sensitive data (e.g., API keys, credentials) is hardcoded or exposed.
- [ ] The branch is up-to-date with the target branch (e.g., staging).
- [ ] The code adheres to established coding standards.

### Pre-merge checklist

- [ ] Two approvals received. (Changes affecting automatic PR verification, like new linter rules, formatting rules, Github workflow configurations)

---

2024-12-18 16:16 UTC, quiteachaos requested changes

2024-12-18 16:16 UTC, quiteachaos commented on test/widgets/cards/summary_preview_card_test.dart
> +        'Then it should display "Income" and primary background color',
add When statements

2024-12-18 16:16 UTC, quiteachaos commented on test/widgets/cards/summary_preview_card_test.dart
> +
also expect that 10 is rendered as +10% in primary color

2024-12-18 16:16 UTC, quiteachaos commented on test/widgets/cards/summary_preview_card_test.dart
> +
also expect +5% is rendered with secondary color

2024-12-18 16:16 UTC, quiteachaos commented on test/widgets/cards/summary_preview_card_test.dart
> +          const percentage = '10';
give it -10 and expect it renders -10% is secondary color

2024-12-18 16:16 UTC, quiteachaos commented on test/widgets/cards/summary_preview_card_test.dart
> +          expect(find.text('₹5000'), findsOneWidget);
₹5,000 should be expected

2024-12-18 16:16 UTC, quiteachaos commented on test/widgets/cards/summary_preview_card_test.dart
> +          const percentage = '10';
send -10 and expect -10% is rendered in primary color

2024-12-18 16:16 UTC, quiteachaos commented on test/widgets/cards/summary_preview_card_test.dart
> +            header: HeaderType.income,
change to headertype.expense

2024-12-18 16:16 UTC, quiteachaos commented on test/widgets/cards/summary_preview_card_test.dart
> +          expect(textWidgets[1].data, contains('₹$amount'));
₹5,000 should be expected not ₹5000.
also the test case is about rendering the vs. last month; so expect that text is rendered properly too

2024-12-18 17:44 UTC, krushnakantanayak commented on test/widgets/cards/summary_preview_card_test.dart
> +        'Then it should display "Income" and primary background color',
done

2024-12-24 20:27 UTC, quiteachaos approved these changes

2024-12-24 20:29 UTC, merged